// Copyright (C) 2026 the Kingdom Come: Deliver Us contributors (AUTHORS). SPDX-License-Identifier: GPL-3.0-only
// GPLv3 section 7 additional terms: NOTICE. This project's own code only; Kingdom Come: Deliverance and its content
// belong to Warhorse Studios and Deep Silver. Unofficial, free, not affiliated with or endorsed by them.
// Modified version of StorySections.cs of Kingdom Come: Together (https://github.com/DeepFriedDepp/KingdomCome-Together):
// the input is a quest code and an objective of the first game, not a quest-State path of the second.
namespace KcdUs.Agent;

/// <summary>How much of a quest keeps the player on rails (docs/quest-gating.md).</summary>
public enum StoryTier
{
    /// <summary>Open-world content: you go where you like.</summary>
    Open,
    /// <summary>Scripted stretches alternate with free ones. A period for the friend's choice; no tether, a shorter idle time.</summary>
    Mixed,
    /// <summary>Staged for its whole run (a battle, a monastery, a tournament, a flashback). A period, the tether, a long idle time.</summary>
    Rails,
}

/// <summary>
/// One quest and whether it keeps the player on rails. Every field is a row of the generated <see cref="QuestCatalog"/>: the game's own
/// quest data, reviewed by hand in docs/quest-gating-plan.csv. The titles are Warhorse's, cited as identifiers only.
/// </summary>
public sealed record StorySection(string Code, string Title, string Kind, StoryTier Tier, string Period, string Why, int Order, string Dlc)
{
    /// <summary>A quest of the main story, in the game's order. A DLC chain is "main" in the data but has no place in that order: it is not main here.</summary>
    public bool IsMain => Kind == "main" && Order > 0;
    public bool Locked => Tier != StoryTier.Open;

    /// <summary>How long the host may do nothing in this section (no new objective) before it is taken as over.</summary>
    public int IdleMs => (IsMain, Tier) switch
    {
        (true, StoryTier.Rails) => 40 * 60 * 1000,
        (true, _) => 12 * 60 * 1000,
        (false, StoryTier.Rails) => 15 * 60 * 1000,
        _ => 8 * 60 * 1000,
    };
}

/// <summary>A locked stretch of the story: what a friend chooses about. <paramref name="Id"/> = the code of its first section.</summary>
public sealed record StoryPeriod(string Id, string Why, IReadOnlyList<string> Codes);

/// <summary>
/// The sections, built from <see cref="QuestCatalog"/> (generated by tools/Build-QuestCatalog.py from the game's data and the plan);
/// nothing here is typed by hand.
/// </summary>
public static class StorySections
{
    private static StorySection Make(QuestRoot q)
    {
        var tier = q.Tier switch { "rails" => StoryTier.Rails, "mixed" => StoryTier.Mixed, _ => StoryTier.Open };
        return new StorySection(q.Code, q.Title, q.Kind, tier, q.Period, tier == StoryTier.Open ? "" : q.Why, q.Order, q.Dlc);
    }

    private static readonly Dictionary<string, StorySection> ByCodeMap =
        QuestCatalog.All.Where(q => q.Kind is "main" or "side" or "activity" or "event").Select(Make)
            .ToDictionary(s => s.Code, StringComparer.OrdinalIgnoreCase);

    /// <summary>The main story in the game's order (locked or not).</summary>
    public static IReadOnlyList<StorySection> Main { get; } =
        ByCodeMap.Values.Where(s => s.IsMain).OrderBy(s => s.Order).ThenBy(s => s.Code, StringComparer.Ordinal).ToArray();

    /// <summary>Every quest that can put the host on rails or in a mixed stretch.</summary>
    public static IReadOnlyList<StorySection> Locked { get; } =
        ByCodeMap.Values.Where(s => s.Locked).OrderBy(s => s.IsMain ? s.Order : 1000).ThenBy(s => s.Code, StringComparer.Ordinal).ToArray();

    /// <summary>The section of a quest: any main quest (the open ones too: they say the story moved on) or any quest that locks. Null for the rest.</summary>
    public static StorySection? ByCode(string? code)
    {
        if (code is null || !ByCodeMap.TryGetValue(code, out var s)) return null;
        return s.IsMain || s.Locked ? s : null;
    }

    public static IReadOnlyList<StoryPeriod> Periods { get; } = BuildPeriods();

    private static readonly Dictionary<string, StoryPeriod> PeriodByCode =
        Periods.SelectMany(p => p.Codes.Select(c => (c, p))).ToDictionary(x => x.c, x => x.p, StringComparer.OrdinalIgnoreCase);

    /// <summary>The period a section belongs to; null for an open quest or an unknown code.</summary>
    public static StoryPeriod? PeriodOf(string? code) => code is not null && PeriodByCode.TryGetValue(code, out var p) ? p : null;

    public static StoryPeriod? PeriodById(string? id) => Periods.FirstOrDefault(p => string.Equals(p.Id, id, StringComparison.Ordinal));

    private static IReadOnlyList<StoryPeriod> BuildPeriods()
    {
        var order = new List<string>();
        var members = new Dictionary<string, List<StorySection>>(StringComparer.Ordinal);
        foreach (var s in Locked)
        {
            if (!members.TryGetValue(s.Period, out var l)) { members[s.Period] = l = new List<StorySection>(); order.Add(s.Period); }
            l.Add(s);
        }
        return order.Select(id => new StoryPeriod(id, members[id][0].Why, members[id].Select(s => s.Code).ToArray())).ToArray();
    }
}

/// <summary>
/// Which section the HOST is in, from the quest changes its game reports (pure; StoryLockTests pin it).
///   * EVIDENCE. A main RAILS quest is entered by its first change. A MIXED quest (and a later open main quest, to count as "the story
///     moved on") needs a burst: <see cref="MixedChanges"/> distinct objectives within <see cref="SustainedWindowMs"/>. A side quest or
///     activity on rails needs <see cref="SideRailsChanges"/>.
///   * A LATER main quest that shows evidence ends the earlier section, and the story is then "at" it.
///   * Another kind of quest enters its own section, unless the host is in a main RAILS section (its world is locked); it replaces another
///     section only when that one has been quiet for <see cref="ReplaceQuietMs"/>.
///   * A quest that completes leaves its section. Nothing NEW from the section for its idle time leaves it.
///   * A side quest or activity is not entered again for a while after it ended (<see cref="CompletedCooldownMs"/>) or idled out
///     (<see cref="IdleCooldownMs"/>).
///   * A load, a disconnect or a world change forgets it (<see cref="Reset"/>).
/// </summary>
public sealed class StoryLock
{
    public const int MixedChanges = 3;
    public const int SideRailsChanges = 2;
    public const int SustainedWindowMs = 90_000;
    public const int ReplaceQuietMs = 30_000;
    public const int CompletedCooldownMs = 90_000;
    public const int IdleCooldownMs = 10 * 60 * 1000;
    private const int RefreshMemory = 8;

    /// <summary>
    /// The leash's warning and pull distances while a rails section holds the joiners close: the tighter of the host's own and the tether.
    /// Off: the host's own, unchanged.
    /// </summary>
    public static (float WarnM, float PullM) Tether(float warnM, float pullM, bool on, float tetherM)
    {
        if (!on) return (warnM, pullM);
        float pull = Math.Min(pullM, tetherM);
        float warn = Math.Min(warnM, Math.Max(50f, tetherM - 30f));
        if (warn >= pull) warn = Math.Max(1f, pull - 1f);
        return (warn, pull);
    }

    public enum Kind { None, Enter, Leave }
    public readonly record struct Transition(Kind Kind, StorySection? Section, string Reason);

    private enum Why { Completed, Idle, Advanced, Replaced }

    private StorySection? _active;
    private long _lastMs;
    private readonly List<string> _refreshed = new();

    public StorySection? Active => _active;

    private int _maxOrder = -1;
    private readonly HashSet<string> _done = new(StringComparer.Ordinal);
    private readonly Dictionary<string, long> _cooldown = new(StringComparer.Ordinal);
    private readonly Dictionary<string, List<(long At, string State)>> _recent = new(StringComparer.Ordinal);

    public void Reset() { _active = null; _maxOrder = -1; _done.Clear(); _cooldown.Clear(); _recent.Clear(); _refreshed.Clear(); }

    private void Close(StorySection a, long nowMs, Why why)
    {
        if (a.IsMain) { if (why is Why.Completed or Why.Advanced) _done.Add(a.Code); }
        else if (why == Why.Completed) _cooldown[a.Code] = nowMs + CompletedCooldownMs;
        else if (why == Why.Idle) _cooldown[a.Code] = nowMs + IdleCooldownMs;
    }

    private void Refresh(string? state, long nowMs)
    {
        if (state is null || _refreshed.Contains(state)) return;
        _refreshed.Add(state);
        if (_refreshed.Count > RefreshMemory) _refreshed.RemoveAt(0);
        _lastMs = nowMs;
    }

    private bool Evidence(StorySection s, string? state, long nowMs)
    {
        int need = s.IsMain && s.Tier == StoryTier.Rails ? 1 : !s.IsMain && s.Tier == StoryTier.Rails ? SideRailsChanges : MixedChanges;
        if (need == 1) return true;
        if (!_recent.TryGetValue(s.Code, out var l)) _recent[s.Code] = l = new List<(long, string)>();
        l.RemoveAll(x => nowMs - x.At > SustainedWindowMs);
        l.Add((nowMs, state ?? ""));
        return l.Select(x => x.State).Distinct().Count() >= need;
    }

    /// <summary>
    /// One change of the host's quest <paramref name="code"/>: <paramref name="state"/> names it (the quest starting, or a new objective's id),
    /// <paramref name="end"/> says the quest completed. Returns what changed: nothing, a Leave, an Enter, or a Leave then an Enter.
    /// </summary>
    public IReadOnlyList<Transition> Note(string? code, string? state, bool end, long nowMs)
    {
        var s = StorySections.ByCode(code);
        if (s is null) return Array.Empty<Transition>();
        var outl = new List<Transition>(2);
        if (s.IsMain && _done.Contains(s.Code)) return outl;
        if (!s.IsMain && _cooldown.TryGetValue(s.Code, out long until) && nowMs < until) return outl;

        if (_active is { } a && s.Code == a.Code)
        {
            if (end) { _active = null; Close(a, nowMs, Why.Completed); outl.Add(new(Kind.Leave, a, "completed")); return outl; }
            Refresh(state, nowMs);
            return outl;
        }
        if (end)
        {
            if (s.IsMain) _done.Add(s.Code); else _cooldown[s.Code] = nowMs + CompletedCooldownMs;
            return outl;
        }

        bool evidence = Evidence(s, state, nowMs);
        if (s.IsMain)
        {
            if (s.Order < _maxOrder) return outl;
            if (s.Order > _maxOrder)
            {
                if (!evidence) return outl;
                _maxOrder = s.Order;
                if (_active is { } old)
                {
                    _active = null;
                    Close(old, nowMs, Why.Advanced);
                    outl.Add(new(Kind.Leave, old, "moved on"));
                }
            }
            else if (_active is { IsMain: false } && nowMs - _lastMs < ReplaceQuietMs) return outl;
        }
        else if (_active is { } cur)
        {
            if (cur.IsMain && cur.Tier == StoryTier.Rails) return outl;
            if (nowMs - _lastMs < ReplaceQuietMs) return outl;
        }

        if (!s.Locked || !evidence) return outl;

        if (_active is { } prev)
        {
            _active = null;
            Close(prev, nowMs, Why.Replaced);
            outl.Add(new(Kind.Leave, prev, "moved on"));
        }
        _active = s; _lastMs = nowMs; _refreshed.Clear();
        if (state is not null) _refreshed.Add(state);
        outl.Add(new(Kind.Enter, s, ""));
        return outl;
    }

    /// <summary>The host did something in the section that is not a quest change (a conversation): it is still there.</summary>
    public void Touch(long nowMs) { if (_active is not null) _lastMs = nowMs; }

    /// <summary>Called about once a second: a section the host has not touched for its idle time is over.</summary>
    public Transition? Tick(long nowMs)
    {
        if (_active is { } a && nowMs - _lastMs > a.IdleMs)
        {
            _active = null;
            Close(a, nowMs, Why.Idle);
            return new Transition(Kind.Leave, a, "idle");
        }
        return null;
    }
}
