# Copyright (C) 2026 the Kingdom Come: Deliver Us contributors (AUTHORS). SPDX-License-Identifier: GPL-3.0-only
# GPLv3 section 7 additional terms: NOTICE. This project's own code only; Kingdom Come: Deliverance and its content
# belong to Warhorse Studios and Deep Silver. Unofficial, free, not affiliated with or endorsed by them.
r"""
Builds the mod folder the game loads: <out>/kcdus/{mod.manifest, mod.cfg, Data/kcdus.pak}.

The pak is a plain zip with forward-slash names; the game mounts only .pak files from Mods/<id>/Data/ and runs
Scripts/Mods/<id>.lua inside it (docs/KCD1-MODDING.md). The build is deterministic: sorted entries, a fixed timestamp,
version.lua written from VERSION. The sha256 of the pak is printed (the installer records it).

    python tools\Build-Pak.py [--out build\mod] [--install-to <game>\Mods] [--debug]

--debug adds -lua_storedebug advice to mod.cfg's comments only; it does not change behaviour.
"""
import argparse, hashlib, os, re, sys, zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LUA_DIR = os.path.join(ROOT, 'mod', 'kcdus', 'lua')
FIXED_TIME = (2026, 1, 1, 0, 0, 0)


def read_version():
    return open(os.path.join(ROOT, 'VERSION'), encoding='utf-8').read().strip()


def pak_entries(version):
    wire = open(os.path.join(ROOT, 'dotnet', 'KcdUs.Protocol', 'Wire.cs'), encoding='utf-8').read()
    match = re.search(r'public const int ProtocolVersion\s*=\s*(\d+)\s*;', wire)
    if not match:
        raise RuntimeError('Cannot determine the authoritative wire version from Wire.cs')
    protocol = int(match.group(1))
    entries = {}
    for name in sorted(os.listdir(LUA_DIR)):
        if not name.endswith('.lua'):
            continue
        data = open(os.path.join(LUA_DIR, name), 'rb').read()
        if name == 'kcdus.lua':
            entries['Scripts/Mods/kcdus.lua'] = data
        elif name == 'version.lua':
            text = ('-- generated by tools/Build-Pak.py\nKCDUS = KCDUS or {}\nKCDUS.VERSION = "%s"\nKCDUS.PROTO = %d\nKCDUS.LUA_BUILD = "pak"\n' % (version, protocol))
            entries['Scripts/Mods/kcdus/version.lua'] = text.encode('utf-8')
        else:
            entries['Scripts/Mods/kcdus/' + name] = data
    return entries


def build_pak(path, entries):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with zipfile.ZipFile(path, 'w', zipfile.ZIP_DEFLATED) as z:
        for name in sorted(entries):
            zi = zipfile.ZipInfo(name, FIXED_TIME)
            zi.create_system = 3  # canonical ZIP metadata across Windows/Linux; handshake hashes must agree
            zi.compress_type = zipfile.ZIP_DEFLATED
            zi.external_attr = 0o644 << 16
            z.writestr(zi, entries[name])


MANIFEST = '''<?xml version="1.0" encoding="utf-8"?>
<kcd_mod>
    <info>
        <name>Kingdom Come: Deliver Us</name>
        <modid>kcdus</modid>
        <description>Co-op for Kingdom Come: Deliverance. Unofficial community mod, not affiliated with Warhorse Studios or Deep Silver.</description>
        <author>the Kingdom Come: Deliver Us contributors</author>
        <version>{version}</version>
        <created_on>2026-10-05</created_on>
    </info>
</kcd_mod>
'''

MODCFG = '''-- Kingdom Come: Deliver Us: the engine's remote console is how the co-op agent sends commands to the game.
-- It listens on TCP 4600 on every address; the installer blocks the port from other machines (docs/KCD1-MODDING.md).
log_EnableRemoteConsole = 1
'''


def build_mod(out, version):
    mod = os.path.join(out, 'kcdus')
    os.makedirs(os.path.join(mod, 'Data'), exist_ok=True)
    open(os.path.join(mod, 'mod.manifest'), 'w', encoding='utf-8', newline='\n').write(MANIFEST.format(version=version))
    open(os.path.join(mod, 'mod.cfg'), 'w', encoding='utf-8', newline='\n').write(MODCFG)
    pak = os.path.join(mod, 'Data', 'kcdus.pak')
    build_pak(pak, pak_entries(version))
    return mod, pak


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default=os.path.join(ROOT, 'build', 'mod'))
    ap.add_argument('--install-to', help='the game\'s Mods folder: copies the built mod there')
    a = ap.parse_args()
    version = read_version()
    mod, pak = build_mod(a.out, version)
    h = hashlib.sha256(open(pak, 'rb').read()).hexdigest()
    print('built %s (%d bytes) sha256 %s' % (pak, os.path.getsize(pak), h))
    if a.install_to:
        import shutil
        dest = os.path.join(a.install_to, 'kcdus')
        shutil.copytree(mod, dest, dirs_exist_ok=True)
        print('installed to', dest)


if __name__ == '__main__':
    main()
